version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "thewisedreams-ai"
github_repo = "sam-app"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::822672882384:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-y8PuNigohOWc"
cloudformation_execution_role = "arn:aws:iam::822672882384:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-FfwuP0BPEdpC"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-walhhzl9ogda"
image_repository = ""
region = "eu-west-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::822672882384:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-fZ9f268W9zkB"
cloudformation_execution_role = "arn:aws:iam::822672882384:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-25DpRTfSHdj6"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-mt0ksmptw4xg"
image_repository = ""
region = "eu-west-1"
